version: "3.8"

networks:
  zy_overlay:
    driver: overlay
    external: true

services:
 chat2api:
  image: 20.210.109.247:5000/library/chat2api:latest
  logging:
   driver: "json-file"
   options:
    max-size: "10m"
    max-file: "100"
  networks:
    - zy_overlay
  deploy:
   resources:
    limits:
     memory: 200M
   mode: replicated
   replicas: 1 
   update_config:
    failure_action: rollback
    order: start-first